language: python
python:
  - "2.7"
env:
  - DJANGO_SETTINGS_MODULE=heartstonearenastats.settings.production
install: 
  - pip install -r requirements.txt
  - pip install flake8 pycopg2
before_script:
  - flake8 ./hearthstonearenastats --exclude='env,migrations'
script:
  - python manage.py test